export const DEFAULT_ITEMS = [
  {id:"i3",v:"Specs",c:"Mixers",n:"Olive Juice",b:0},
  {id:"i4",v:"Twin Liquor",c:"Mixers",n:"Blueberry Simple",b:0},
  {id:"i6",v:"Amazon",c:"Mixers",n:"Cherries",b:0},
  {id:"i7",v:"Amazon",c:"Mixers",n:"Dried Lavender",b:0},
  {id:"i8",v:"Amazon",c:"Mixers",n:"Pea Flower Powder",b:0},
  {id:"i9",v:"Amazon",c:"Cleaning",n:"Microfiber Towels",b:0},
  {id:"i10",v:"Amazon",c:"Gloves",n:"Small - Rubber Gloves",b:0},
  {id:"i11",v:"Amazon",c:"Gloves",n:"Medium - Rubber Gloves",b:0},
  {id:"i12",v:"Amazon",c:"Gloves",n:"Large - Rubber Gloves",b:0},
  {id:"i13",v:"Amazon",c:"Gloves",n:"X-Large - Rubber Gloves",b:0},
  {id:"i14",v:"Amazon",c:"Picks",n:"Bamboo cocktail picks",b:0},
  {id:"i15",v:"Amazon",c:"Straws",n:"Reusable straws (Sugar Cane)",b:0},
  {id:"i16",v:"Amazon",c:"Cups",n:"Wine Cups",b:0},
  {id:"i17",v:"Amazon",c:"Ice Bags",n:"Ice Bags",b:0},
  {id:"i18",v:"Amazon",c:"Gas",n:"Butane",b:0},
  {id:"i19",v:"Amazon",c:"Acid",n:"Citric Acid",b:0},
  {id:"i20",v:"Amazon",c:"Acid",n:"Malic Acid",b:0},
  {id:"i22",v:"Kombucha",c:"Kombucha",n:"Ginger Spice",b:0},
  {id:"i23",v:"Kombucha",c:"Kombucha",n:"Groovy Green",b:0},
  {id:"i24",v:"Kombucha",c:"Kombucha",n:"Ms. Pink",b:0},
  {id:"i25",v:"Kombucha",c:"Kombucha",n:"Sway Home",b:0},
  {id:"i26",v:"Kombucha",c:"Kombucha",n:"Cosmic Black",b:0},
  {id:"i28",v:"Tincture",c:"Tincture",n:"Heart",b:0},
  {id:"i29",v:"Tincture",c:"Tincture",n:"Lung",b:0},
  {id:"i30",v:"Tincture",c:"Tincture",n:"Kidney",b:0},
  {id:"i31",v:"Tincture",c:"Tincture",n:"Spleen",b:0},
  {id:"i32",v:"Tincture",c:"Tincture",n:"Liver",b:0},
  {id:"i34",v:"ECOLAB",c:"Dishwasher",n:"Trump",b:0},
  {id:"i35",v:"ECOLAB",c:"Dishwasher",n:"San",b:0},
  {id:"i36",v:"ECOLAB",c:"Dishwasher",n:"Rinse",b:0},
  {id:"i37",v:"ECOLAB",c:"Dishwasher",n:"Lime-A-Way",b:0},
  {id:"i38",v:"ECOLAB",c:"Dishwasher",n:"Red Sani/Multi Quat",b:0},
  {id:"i40",v:"RNDC",c:"Wine",n:"Chardonnay",b:0},
  {id:"i41",v:"RNDC",c:"Wine",n:"Cabernet",b:0},
  {id:"i42",v:"RNDC",c:"Wine",n:"Rose",b:0},
  {id:"i43",v:"RNDC",c:"Wine",n:"Sparkling",b:0},
  {id:"i45",v:"Kwik Ice",c:"Ice",n:"Cube Ice",b:0},
  {id:"i47",v:"Sams Club",c:"Paper Towels",n:"Round Bathroom Towels",b:0},
  {id:"i48",v:"Sams Club",c:"Hand Soap",n:"Hand Soap Bulk",b:0},
  {id:"i50",v:"Odeko",c:"Paper Towels",n:"Kraft Multi-fold Towels",b:0},
  {id:"i51",v:"Odeko",c:"Hand Soap",n:"Karat Hand Wash 1 Gal",b:0},
  {id:"i52",v:"Odeko",c:"Stir Sticks",n:"Karat Wood Stir Sticks",b:0},
  {id:"i53",v:"Odeko",c:"Cup Holder",n:"Karat 4 Cup Holder",b:0},
  {id:"i54",v:"Odeko",c:"Cup Jackets",n:"Karat Cup Jackets",b:0},
  {id:"i55",v:"Odeko",c:"Straws",n:"Karat Giant Clear Straw",b:0},
  {id:"i56",v:"Odeko",c:"Hot Lids",n:"Solo Black Hot Lid 8oz",b:0},
  {id:"i57",v:"Odeko",c:"Hot Lids",n:"Solo White Hot Lid 12-20oz",b:0},
  {id:"i58",v:"Odeko",c:"Hot Cups",n:"Solo Hot Cup 4oz",b:0},
  {id:"i59",v:"Odeko",c:"Hot Cups",n:"Solo Hot Cup 8oz",b:0},
  {id:"i60",v:"Odeko",c:"Hot Cups",n:"Solo Hot Cup 12oz",b:0},
  {id:"i61",v:"Odeko",c:"Hot Cups",n:"Solo Hot Cup 16oz",b:0},
  {id:"i62",v:"Odeko",c:"Cold Cups",n:"Karat Cold Cup 12oz",b:0},
  {id:"i63",v:"Odeko",c:"Cold Cups",n:"Karat Cold Cup 16oz",b:0},
  {id:"i64",v:"Odeko",c:"Cold Lids",n:"Karat Cold Cup Lid 12-24oz",b:0},
  {id:"i65",v:"Odeko",c:"Syrup",n:"Monin SF Chocolate Syrup",b:0},
  {id:"i66",v:"Odeko",c:"Syrup",n:"Monin Vanilla Syrup",b:0},
  {id:"i67",v:"Odeko",c:"Chai",n:"David Rio Chai 1:5",b:0},
  {id:"i68",v:"Odeko",c:"Matcha",n:"Mighty Leaf Matcha 1lb",b:0},
  {id:"i69",v:"Odeko",c:"Oat Milk",n:"Oatly Barista Oat Milk",b:0},
  {id:"i70",v:"Odeko",c:"Tea",n:"Green",b:0},
  {id:"i71",v:"Odeko",c:"Tea",n:"Black",b:0},
  {id:"i72",v:"Odeko",c:"Tea",n:"Grey",b:0},
  {id:"i73",v:"Odeko",c:"Tea",n:"Chamomile",b:0},
  {id:"i75",v:"Greater Goods",c:"Coffee",n:"Coffee 5lb",b:0},
  {id:"i76",v:"Greater Goods",c:"Coffee",n:"Coffee 2lb Decaf",b:0},
  {id:"i77",v:"Greater Goods",c:"Cleaner",n:"Red Cleaner",b:0},
  {id:"i78",v:"Greater Goods",c:"Cleaner",n:"Yellow Cleaner",b:0},
  {id:"i79",v:"Greater Goods",c:"Cleaner",n:"Blue Cleaner",b:0},
  {id:"i81",v:"HEB",c:"Frozen Fruit",n:"16oz Frozen Strawberry",b:0},
  {id:"i82",v:"HEB",c:"Frozen Fruit",n:"16oz Frozen Wild Blueberry",b:0},
  {id:"i83",v:"HEB",c:"Fruit",n:"Grapefruit",b:0},
  {id:"i84",v:"HEB",c:"Fruit",n:"Oranges",b:0},
  {id:"i85",v:"HEB",c:"Fruit",n:"Lemons",b:0},
  {id:"i86",v:"HEB",c:"Fruit",n:"Limes",b:0},
  {id:"i87",v:"HEB",c:"Produce",n:"Cucumbers",b:0},
  {id:"i88",v:"HEB",c:"Produce",n:"Mint",b:0},
  {id:"i89",v:"HEB",c:"Produce",n:"Olives",b:0},
  {id:"i90",v:"HEB",c:"Produce",n:"Habanero",b:0},
  {id:"i91",v:"HEB",c:"Produce",n:"Jalapeno",b:0},
  {id:"i92",v:"HEB",c:"Bitters",n:"Angostura Bitters",b:0},
  {id:"i93",v:"HEB",c:"Syrup",n:"Pomegranate Syrup",b:0},
  {id:"i94",v:"HEB",c:"Syrup",n:"Honey",b:0},
  {id:"i95",v:"HEB",c:"Syrup",n:"Maple Syrup",b:0},
  {id:"i96",v:"HEB",c:"Spices",n:"Vanilla Extract",b:0},
  {id:"i97",v:"HEB",c:"Sugar",n:"Agave",b:0},
  {id:"i98",v:"HEB",c:"Sugar",n:"Sugar 10# Hill Country Fair",b:0},
  {id:"i99",v:"HEB",c:"Sugar",n:"Dark Brown Sugar",b:0},
  {id:"i100",v:"HEB",c:"Juice",n:"Simply Orange",b:0},
  {id:"i101",v:"HEB",c:"Juice",n:"Pineapple Juice",b:0},
  {id:"i102",v:"HEB",c:"Juice",n:"Grapefruit Juice",b:0},
  {id:"i103",v:"HEB",c:"Juice",n:"Cranberry Juice",b:0},
  {id:"i104",v:"HEB",c:"Juice",n:"Pomegranate Juice",b:0},
  {id:"i105",v:"HEB",c:"Juice",n:"Mango Nectar",b:0},
  {id:"i106",v:"HEB",c:"Juice",n:"Peach Nectar",b:0},
  {id:"i107",v:"HEB",c:"Juice",n:"Pear Nectar",b:0},
  {id:"i108",v:"HEB",c:"Soda",n:"Maine Root Beer",b:0},
  {id:"i109",v:"HEB",c:"Soda",n:"Mexican Coke",b:0},
  {id:"i110",v:"HEB",c:"Soda",n:"Blueberry Soda",b:0},
  {id:"i111",v:"HEB",c:"Soda",n:"Fever Tree Ginger Beer",b:0},
  {id:"i112",v:"HEB",c:"Dairy",n:"Heavy Whipping Cream",b:0},
  {id:"i113",v:"HEB",c:"Sweetener",n:"Equal",b:0},
  {id:"i114",v:"HEB",c:"Sweetener",n:"Splenda",b:0},
  {id:"i115",v:"HEB",c:"Sweetener",n:"Sweet'N Low",b:0},
  {id:"i116",v:"HEB",c:"Sweetener",n:"Raw Sugar",b:0},
  {id:"i117",v:"HEB",c:"Sweetener",n:"Cinnamon Powder",b:0},
  {id:"i118",v:"HEB",c:"Cleaning",n:"Trash Bags Big (Black)",b:0},
  {id:"i119",v:"HEB",c:"Cleaning",n:"Trash Bags Little (White)",b:0},
  {id:"i120",v:"HEB",c:"Cleaning",n:"Trash Bags 4 Gal",b:0},
  {id:"i121",v:"HEB",c:"Cleaning",n:"Floor Cleaner",b:0},
  {id:"i122",v:"HEB",c:"Cleaning",n:"Dish Soap",b:0},
  {id:"i123",v:"HEB",c:"Cleaning",n:"Toilet Paper",b:0},
  {id:"i124",v:"HEB",c:"Cleaning",n:"Dish Sponges",b:0},
  {id:"i125",v:"HEB",c:"Drink Addition",n:"Tajin",b:0},
  {id:"i126",v:"HEB",c:"Drink Addition",n:"Salt",b:0},
  {id:"i127",v:"HEB",c:"Drink Addition",n:"Chamoy",b:0},
  {id:"i128",v:"HEB",c:"Drink Addition",n:"Ginger Candy",b:0},
  {id:"i129",v:"HEB",c:"Other",n:"Taco Bags",b:0},
  {id:"i130",v:"HEB",c:"Dairy",n:"Whole Milk",b:0},
  {id:"i131",v:"HEB",c:"Produce",n:"Garlic",b:0},
  {id:"i132",v:"HEB",c:"Produce",n:"Cilantro",b:0},
  {id:"i133",v:"HEB",c:"Produce",n:"Serrano",b:0},
  {id:"i134",v:"HEB",c:"Produce",n:"Tomatillo",b:0},
  {id:"i135",v:"HEB",c:"Produce",n:"Avocado",b:0},
  {id:"i136",v:"HEB",c:"Soda",n:"Rambler Grapefruit",b:0},
  {id:"i137",v:"HEB",c:"Mixer",n:"Fee Foam",b:0},
  {id:"i138",v:"HEB",c:"Mixer",n:"Bloody Mary",b:0},
  {id:"i139",v:"HEB",c:"Mixer",n:"Hot Cocoa",b:0},
  {id:"i140",v:"HEB",c:"Mixer",n:"Apple Cider Mix",b:0},
  {id:"i141",v:"HEB",c:"Produce",n:"Thyme",b:0},
  {id:"i142",v:"HEB",c:"Cleaning",n:"Paper Towels",b:0},
  {id:"i143",v:"HEB",c:"Juice",n:"Apple Cider (Juice)",b:0},
  {id:"i144",v:"HEB",c:"Syrup",n:"Pistachio Syrup",b:0},
  {id:"i145",v:"HEB",c:"Soda",n:"Topo Chico",b:0},
  {id:"i146",v:"HEB",c:"Spices",n:"Crushed Red Pepper Flakes",b:0},
  {id:"i147",v:"HEB",c:"Sweetener",n:"Caramel",b:0},
  {id:"i148",v:"HEB",c:"Garnish",n:"Marshmallow",b:0},
  {id:"i149",v:"HEB",c:"Spices",n:"Cinnamon Stick",b:0},
  {id:"i150",v:"HEB",c:"Spices",n:"Almond Extract",b:0},
  {id:"i151",v:"HEB",c:"Spices",n:"Vanilla Paste",b:0},
  {id:"i152",v:"HEB",c:"Produce",n:"Raspberries",b:0},
  {id:"i153",v:"HEB",c:"Mixer",n:"Orange Flower Water",b:0},
  {id:"i154",v:"HEB",c:"Dairy",n:"Butter",b:0},
  {id:"i155",v:"HEB",c:"Spices",n:"Cardamom",b:0},
  {id:"i156",v:"HEB",c:"Spices",n:"Star Anise",b:0},
  {id:"i157",v:"HEB",c:"Spices",n:"Cloves",b:0},
  {id:"i158",v:"HEB",c:"Cleaner",n:"Sanitizer (Seventh Gen)",b:0},
  {id:"i159",v:"HEB",c:"Cleaner",n:"Toilet Cleaner (Seventh Gen)",b:0},
  {id:"i160",v:"HEB",c:"Cleaner",n:"Glass Cleaner",b:0},
  {id:"i161",v:"HEB",c:"Cleaner",n:"Bleach",b:0},
  {id:"i162",v:"HEB",c:"Cleaner",n:"Isopropyl Alcohol",b:0},
  {id:"i163",v:"HEB",c:"Cleaner",n:"Barkeepers Friend",b:0},
  {id:"i164",v:"HEB",c:"Cleaner",n:"Silver Shine",b:0},
  {id:"i165",v:"HEB",c:"Soda",n:"Tonic Water",b:0},
  {id:"i166",v:"HEB",c:"Produce",n:"Apples",b:0},
  {id:"i168",v:"Other",c:"N/A Beer",n:"Athletic",b:0},
  {id:"i169",v:"Amazon",c:"Other",n:"Stamp Pad",b:0},
  {id:"i170",v:"HEB",c:"Spices",n:"Nutmeg",b:0},
  {id:"i171",v:"Amazon",c:"Packaging",n:"Bottle Bags Paper",b:0},
  {id:"i172",v:"Amazon",c:"Packaging",n:"Bottle Bags Plastic",b:0},
  {id:"i173",v:"HEB",c:"Snacks",n:"Chip Variety Bag",b:0},
  {id:"i174",v:"Specs",c:"Spirits",n:"Sweet Vermouth",b:0},
  {id:"i175",v:"Specs",c:"Spirits",n:"Dry Vermouth",b:0},
];

export const VENDOR_COLORS = {
  "HEB":"#e03131","Amazon":"#f08c00","Odeko":"#2b8a3e","RNDC":"#7048e8",
  "ECOLAB":"#1971c2","Greater Goods":"#0c8599","Kombucha":"#e8590c",
  "Tincture":"#9c36b5","Specs":"#d6336c","Twin Liquor":"#5c940d",
  "Kwik Ice":"#3bc9db","Sams Club":"#4263eb","Other":"#868e96",
};
